### ISSUE TITLE
mamba should explicitly depend on conda 4.6+

### ISSUE THREAD

**Issue by yuvipanda** [QuantStack/mamba#18]
Running --version fails:

```
+ conda --version
Traceback (most recent call last):
  File "/root/.local/bin/conda", line 8, in <module>
    from mamba.mamba import main
  File "/srv/conda/lib/python3.7/site-packages/mamba/mamba.py", line 23, in <module>
    from conda.base.constants import ChannelPriority
ImportError: cannot import name 'ChannelPriority' from 'conda.base.constants' (/srv/conda/lib/python3.7/site-packages/conda/base/constants.py)

```

**Comment by yuvipanda** [comment]
Ah, it looks like mamba depends on 4.6+ of conda, but doesn't specify that in its dependencies. This error is with 4.5.x

**Comment by wolfv** [comment]
Thanks!

**Comment by wolfv** [comment]
updated in the new recipe: https://github.com/conda-forge/mamba-feedstock/pull/4/files#diff-e178b687b10a71a3348107ae3154e44cR28
