### ISSUE TITLE
repoquery fails with `-c` of existing channel

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#186]
```
% mamba repoquery -c conda-forge conda-smithy

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
<priv>      [====================] (00m:00s) No change
<priv>      [====================] (00m:00s) 404 Ignored
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 754, in exception_converter
        raise e
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 748, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 718, in _wrapped_main
        exit_code = do_call(args, p)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 639, in do_call
        exit_code = repoquery(args, parser)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 608, in repoquery
        repo = api.Repo(pool, str(channel), subdir.cache_path(), channel.url(with_credentials=True))
    RuntimeError: Cache not loaded!

`$ /Users/uwe/miniconda3/bin/mamba repoquery -c conda-forge conda-smithy`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/uwe/miniconda3/bin/conda
             CONDA_PREFIX=/Users/uwe/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
   CONDA_PYTHONBREAKPOINT=
         CONDA_PYTHON_EXE=/Users/uwe/miniconda3/bin/python
               CONDA_ROOT=/Users/uwe/miniconda3
              CONDA_SHLVL=1
                     PATH=/Users/uwe/miniconda3/bin:/Users/uwe/miniconda3/condabin:/usr/local/bi
                          n:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
         PYTHONBREAKPOINT=ipdb.set_trace
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/uwe/miniconda3
            shell level : 1
       user config file : /Users/uwe/.condarc
 populated config files : /Users/uwe/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.4
       base environment : /Users/uwe/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          … snip …
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/uwe/miniconda3/pkgs
                          /Users/uwe/.conda/pkgs
       envs directories : /Users/uwe/miniconda3/envs
                          /Users/uwe/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/19.4.0 OSX/10.15.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

Using `mamba repoquery -c conda-forge --override-channels conda-smithy` works though.

**Comment by wolfv** [comment]
fixed on master. now I am fixing the segfault on OS X and then there will be a new release :)
