### ISSUE TITLE
mamba not ignoring empty channels on disk

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#201]
If I have a local channel on disk that only has `noarch` packages, `mamba` insists that there must also be a `repodata.json` for the subdir.

Similar to #180 but there it was `http`.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/mamba/mamba.py", line 766, in exception_converter
        raise e
      File "/opt/conda/lib/python3.7/site-packages/mamba/mamba.py", line 760, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/mamba/mamba.py", line 730, in _wrapped_main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.7/site-packages/mamba/mamba.py", line 637, in do_call
        exit_code = install(args, parser, 'install')
      File "/opt/conda/lib/python3.7/site-packages/mamba/mamba.py", line 398, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/conda/lib/python3.7/site-packages/mamba/utils.py", line 52, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (37) Couldn't read a file:// file [file:///…/linux-64/repodata.json]
```

**Comment by wolfv** [comment]
this should be fixed in master, release should be out today.
