### ISSUE TITLE
JSON from old-style noarch packages

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#258]
I think the JSON of old-style noarch packages isn't implemented correctly. 

E.g. for `path.py-12.4.0-0`, which comes with `anaconda`.

```
Linking path.py-12.4.0-0

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/wolfv/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 786, in exception_converter
        raise e
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 780, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 746, in _wrapped_main
        exit_code = do_call(args, p)
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 651, in do_call
        exit_code = create(args, parser)
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 571, in create
        install(args, parser, 'create')
      File "/home/wolfv/Programs/mamba/mamba/mamba.py", line 544, in install
        transaction.execute(prefix_data, PackageCacheData.first_writable().pkgs_dir)
    RuntimeError: [json.exception.type_error.302] type must be string, but is boolean
```

**Comment by wolfv** [comment]
Fixed, although we still don't (and probably won't) support pre-link scripts which  might be necessary for true V1 noarch packages.
