### ISSUE TITLE
Dependency specification unsupported? mamba install blas=*=openblas

### ISSUE THREAD

**Issue by consideRatio** [QuantStack/mamba#29]
This project is awesome! Thank you for working on this! It is a BIG DEAL I think! :heart: Anyhow, while trying it out I ended up with an error so here comes a report about that error.

It seems to me that `mamba` cannot manage installing a package where dependencies are specified like here: `mamba install blas=*=openblas`, this is possible with `conda` though. When I ran `mamba --version` I got output about `conda 4.6.14`. Mamba was installed today.

```
$ mamba install blas=*=openblas
                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  https://conda.anaconda.org/conda-forge/linux-64
Getting  https://conda.anaconda.org/conda-forge/noarch
Getting  https://repo.anaconda.com/pkgs/main/linux-64
Getting  https://repo.anaconda.com/pkgs/main/noarch
Getting  https://repo.anaconda.com/pkgs/free/noarch
Getting  https://repo.anaconda.com/pkgs/free/linux-64
Getting  https://repo.anaconda.com/pkgs/r/linux-64
Getting  https://repo.anaconda.com/pkgs/r/noarch

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/mamba/mamba.py", line 353, in _wrapped_main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.6/site-packages/mamba/mamba.py", line 332, in do_call
        exit_code = install(args, parser, 'install')
      File "/opt/conda/lib/python3.6/site-packages/mamba/mamba.py", line 237, in install
        mamba_solve_specs = [s.conda_build_form() for s in specs]
      File "/opt/conda/lib/python3.6/site-packages/mamba/mamba.py", line 237, in <listcomp>
        mamba_solve_specs = [s.conda_build_form() for s in specs]
      File "/opt/conda/lib/python3.6/site-packages/conda/models/match_spec.py", line 360, in conda_build_form
        assert version
    AssertionError

`$ /opt/conda/bin/mamba install blas=*=openblas`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_DIR=/opt/conda
               CONDA_ROOT=/opt/conda
                     PATH=/home/jovyan/.local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:
                          /usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.7.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.6.7 Linux/4.14.94+ ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:100
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
Hi, thanks for opening this issue. 

I think I found a workaround -- using `blas=*.*=openblas`.

I am currently using a conda-internal function to convert the matchspec to what they call the `conda_build_form` and that doesn't seem to work for this particular case. However, passing the above yields the "correct" form which is 

`blas * openblas`

Thanks for the kind words!
