### ISSUE TITLE
mamba cannot install "libblas=*=*mkl"

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#318]
This leads to the following error:

```
Looking for: ['libblas']


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 812, in exception_converter
        raise e
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 806, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 772, in _wrapped_main
        exit_code = do_call(args, p)
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 672, in do_call
        exit_code = install(args, parser, 'install')
      File "/Users/uwe/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 536, in install
        solver.add_jobs(mamba_solve_specs, solver_task)
    RuntimeError: Invalid spec, no package name found: libblas=

`$ /Users/uwe/miniconda3/condabin/mamba install libblas=*=*mkl`
```

**Comment by wolfv** [comment]
thanks for finding this, that's an issue with our match spec implementation.

**Comment by wolfv** [comment]
This is actually a corner case on the string representation of MatchSpecs in conda it seems. 

When we have a spec like `libblas=*=*mkl`, conda's MatchSpec translates it to `libblas=[build=*mkl]`.
Therefore the version information isn't properly represented, and parsing this MatchSpec again fails.

e.g.

```
>>> import conda
>>> from conda.models.match_spec import MatchSpec
>>> MatchSpec('libblas=*=*mkl')
MatchSpec("libblas=[build=*mkl]")
>>> a = _
>>> a.conda_build_form()
'libblas * *mkl'
>>> MatchSpec("libblas=[build=*mkl]")
MatchSpec("libblas[build=*mkl]")
>>> b = _
>>> b.conda_build_form()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wolfv/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 369, in conda_build_form
    assert version
AssertionError
```

So to fix this properly we probably should make a PR to conda itself. I'll see what we can do on mamba's side.

**Comment by wolfv** [comment]
This would work:

```
>>> c = MatchSpec("libblas=*[build=*mkl]")
>>> c.conda_build_form()
'libblas * *mkl'
```
