### ISSUE TITLE
Minimamba first run file exists

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#35]
When running a fresh minimamba, multiple threads might try to create minimamba/pkgs/cache

We need to add a lock I guess.

**Comment by davidbrochart** [comment]
Or use `os.makedirs(exist_ok=True)`? Still, I don't know what happens when several threads do it simultaneously.

**Comment by toupeiro** [comment]
Hello,

I just wanted to add a +1 here. I get a core dump as well which is kinda cool on CentOS 6 and 7.  anything specific I can provide you to help remedy this?

**Comment by nh13** [comment]
Ditto, also getting a core dump after a fresh install of miniconda and then mamba.

**Comment by buhrmann** [comment]
Might this be related to the "file exists..." and permission-related errors I get after installing mamba in an existing conda environment? Here the trace, in case it helps (install seems to have been successful anyway, and very fast 😁):

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/utils.py", line 20, in get_channel
    return result_container.append(FastSubdirData(Channel(x)).load())
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/FastSubdirData.py", line 63, in __call__
    subdir_data_instance = super(SubdirDataType, cls).__call__(channel)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/FastSubdirData.py", line 81, in __init__
    self.cache_path_base = join(create_cache_dir(),
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/core/subdir_data.py", line 595, in create_cache_dir
    mkdir_p_sudo_safe(cache_dir)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
    os.mkdir(path)
FileExistsError: [Errno 17] File exists: '/Users/thomas/anaconda/envs/grapy/pkgs/cache'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 107, in touch
    mkdir_p_sudo_safe(dirpath)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
    os.mkdir(path)
FileExistsError: [Errno 17] File exists: '/Users/thomas/anaconda/envs/grapy/pkgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/utils.py", line 20, in get_channel
    return result_container.append(FastSubdirData(Channel(x)).load())
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/FastSubdirData.py", line 63, in __call__
    subdir_data_instance = super(SubdirDataType, cls).__call__(channel)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/mamba/FastSubdirData.py", line 81, in __init__
    self.cache_path_base = join(create_cache_dir(),
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/core/subdir_data.py", line 594, in create_cache_dir
    cache_dir = join(PackageCacheData.first_writable(context.pkgs_dirs).pkgs_dir, 'cache')
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 154, in first_writable
    created = create_package_cache_directory(package_cache.pkgs_dir)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 409, in create_package_cache_directory
    touch(join(pkgs_dir, PACKAGE_CACHE_MAGIC_FILE), mkdir=True, sudo_safe=sudo_safe)
  File "/Users/thomas/anaconda/envs/grapy/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 125, in touch
    raise NotWritableError(path, e.errno, caused_by=e)
conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.
  path: /Users/thomas/anaconda/envs/grapy/pkgs/urls.txt
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /Users/thomas/anaconda/envs/grapy/pkgs/urls.txt

In general, it's not advisable to use 'sudo conda'.
```

**Comment by wolfv** [comment]
I think this is solved with the last release.
